name: vaultbank
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  flutter_bloc: ^9.1.1
  crypto: ^3.0.6
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  equatable: ^2.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/action_button/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 700
    - family: NunitoSans
      fonts:
        # - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        #   weight: 400   
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 700  
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic

# buat icon aplikasi
flutter_launcher_icons:
  android: "launcher_icon"   
  ios: true                 
  image_path: "assets/images/icon_logo.png" 
  min_sdk_android: 21       
